# Generated by Django 2.1 on 2021-07-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20210710_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted']},
        ),
    ]
