# Generated by Django 2.1 on 2021-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20210711_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
