# Generated by Django 2.1 on 2021-07-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20210711_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploadpro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
        ),
    ]
