# Generated by Django 2.1 on 2021-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_post_uploadpro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploadpro',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='userProfiles/test.png', null=True, upload_to='userProfiles/'),
        ),
    ]
