# Generated by Django 2.1 on 2021-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_auto_20210711_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
